### ISSUE TITLE
Setup Error - github_api (LoadError)

### ISSUE THREAD

**Issue by ianherbert** [keslerm/githabit#11]
Hi there,

Thanks for making this tool!

I've been trying to get it installed via the instructions in the Readme, and after doing sudo gem install githabit, I then run githabit --setup and get the following error:

Any idea what I'm missing, or what info would be useful for debugging?

Thanks
Ian

:~$ githabit --setup
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- github_api (LoadError)
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/githabit-0.3.0/lib/githabit/github_api.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/githabit-0.3.0/lib/githabit/app.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/githabit-0.3.0/lib/githabit.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/githabit-0.3.0/exe/githabit:4:in `<top (required)>'
	from /usr/local/bin/githabit:23:in `load'
	from /usr/local/bin/githabit:23:in `<main>'

**Comment by keslerm** [comment]
Looks like you are missing the github API though it should have installed automatically.

Try

> gem install github_api

and give it another run.

**Comment by ianherbert** [comment]
Cheers Morgan,

I had to go through and install each dependency with root priviledges for some reason.

**Comment by keslerm** [comment]
Looks like i had the wrong dependency type in the gemspec (learned something new today) - updated version should install required dependencies now.

Thanks for pointing that out!
